<h2>item</h2>
<p>If a search query has results, the items array of the response will be populated with a collection of item objects. Each item object is a summary of the metadata in the Europeana repository for that item. The actual content of the item object depends on the profile parameter sent in the <a href="/documentation/search.json#request">search request</a>. <span class="todo">more explanation needed - what is this, why would i use it, any online references to it</span></p>

<table class="bordered">

	<thead>

		<tr>
			<th>properties</th>
			<th>data&nbsp;type</th>
			<th>description</th>
		</tr>

	</thead>

	<tbody>

			<tr>
				<td>completeness <span class="required">*</span></td>
				<td>int</td>
				<td>Completeness is a number, from 1 to 10, measuring the quality of metadata records by the completeness of mandatory and optional metadata schema fields.</td>
			</tr>

			<tr>
				<td>dataProvider <span class="required">*</span></td>
				<td>array</td>
				<td>A collection of <a href="http://www.europeana.eu/portal/europeana-providers.html" title="data providers" target="_blank">Europeana Data Providers</a> : the name or identifier of the data provider of the object (i.e. the organisation providing data to an aggregator). Identifiers will not be available until Europeana has implemented its Organisation profile. (min 1, max 1) [<a href="http://pro.europeana.eu/documents/900548/ea68f42d-32f6-4900-91e9-ef18006d652e" title="EDM Guidelines v1.0.1.pdf">EDM Guidelines v1.0.1.pdf</a>, pg 16]</td>
			</tr>

			<tr>
				<td>europeanaCollectionName&nbsp;<span class="required">*</span></td>
				<td>array</td>
				<td>A collection of europeana collection names : <span class="todo">need to define</span></td>
			</tr>

			<tr>
				<td>guid <span class="required">*</span></td>
				<td>string</td>
				<td>a url pointing to the object page in portal, and includes "utm_source=api&utm_medium=api&utm_campaign=BNVFJIIZTH" parameters to track the API-generated visits. This way Europeana and partners can measure the traffic generated by the API, so please keep these parameters as the part of the link.</td>
			</tr>

			<tr>
				<td>id <span class="required">*</span></td>
				<td>string</td>
				<td>The item record id <span class="todo">need to define</span></td>
			</tr>

			<tr>
				<td>link <span class="required">*</span></td>
				<td>string</td>
				<td>an URL points to the object call in API. If you want to retrieve the full metadata object, please follow this link. The link contains the API key, so you should no display directly to the end users.</td>
			</tr>

			<tr>
				<td>provider <span class="required">*</span></td>
				<td></td>
				<td>The name or identifier of the provider of the object(i.e. the organisation providing data directly to Europeana). Identifiers will not be available until Europeana has implemented its Organisation profile. (min 1, max 1) [<a href="http://pro.europeana.eu/documents/900548/ea68f42d-32f6-4900-91e9-ef18006d652e" title="EDM Guidelines v1.0.1.pdf">EDM Guidelines v1.0.1.pdf</a>, pg 17]</td>
			</tr>

			<tr>
				<td>rights <span class="required">*</span></td>
				<td>array</td>
				<td>A collection of urls referring to the allowed rights to the object <span class="todo">need to define</span></td>
			</tr>

			<tr>
				<td>type <span class="required">*</span></td>
				<td>string</td>
				<td>The provided object is one of the types accepted by Europeana and will govern which facet it appears under in the portal [TEXT, VIDEO, SOUND, IMAGE, 3D] (min 1, max 1) [<a href="http://pro.europeana.eu/documents/900548/ea68f42d-32f6-4900-91e9-ef18006d652e" title="EDM Guidelines v1.0.1.pdf">EDM Guidelines v1.0.1.pdf</a>, pg 12] For 3D also see <a href="http://dublincore.org/documents/dces/" target="_blank">dc:format</a></td>
			</tr>

			<tr>
				<td>dcCreator</td>
				<td>array</td>
				<td>A collection fo dc:creators : An entity primarily responsible for making the resource. Examples of a Creator include a person, an organization, or a service. Typically, the name of a Creator should be used to indicate the entity. <a href="http://dublincore.org/documents/dces/#creator" target="_blank">dc:creator</a></td>
			</tr>

			<tr>
				<td>edmConceptLabel</td>
				<td><span class="todo">need to define</span></td>
				<td><span class="todo">need to define</span></td>
			</tr>

			<tr>
				<td>edmPreview</td>
				<td><span class="todo">need to define</span></td>
				<td><span class="todo">need to define</span></td>
			</tr>

			<tr>
				<td>edmTimespanLabel</td>
				<td><span class="todo">need to define</span></td>
				<td><span class="todo">need to define</span></td>
			</tr>

			<tr>
				<td>europeanaCompleteness</td>
				<td><span class="todo">need to define</span></td>
				<td><span class="todo">need to define</span></td>
			</tr>

			<tr>
				<td>index</td>
				<td>int</td>
				<td><span class="todo">need to define</span></td>
			</tr>

			<tr>
				<td>language</td>
				<td>array</td>
				<td>A collection of languages that refer to ?<span class="todo">need to define</span></td>
			</tr>

			<tr>
				<td>title</td>
				<td>array</td>
				<td>A collection of string titles that refer to the item <span class="todo">need to define</span></td>
			</tr>

			<tr>
				<td>year</td>
				<td>int <span class="todo">need to define</span></td>
				<td>The year the item was ?<span class="todo">need to define</span></td>
			</tr>

		</tbody>

</table>
<span class="required">*</span> <small>indicates an object property guaranteed to be in the object</small>
